export default {
  GET_POST_SUCCESS: "GET_POST_SUCCESS",
  GET_POST_FAILED: "GET_POST_FAILED",
  CREATE_POST_SUCCESS: "CREATE_POST_SUCCESS",
  CREATE_POST_FAILED: "CREATE_POST_FAILED",
  POST_DETAILS_FAILED: "POST_DETAILS_FAILED",
  POST_DETAILS_SUCCESS: "POST_DETAILS_SUCCESS",

  REMOVE_POST_DATA_SUCCESS_FAILED: "REMOVE_POST_DATA_SUCCESS_FAILED",
};
